server:
  port: ${HTTP_SERVER_PORT:8080}
  forward-headers-strategy: framework
  shutdown: graceful

spring:
  application:
    name: expiro-chat-tuna
  datasource:
    name: primaryDS
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${DATABASE_MAX_POOL_SIZE:5}
      schema: ${DATABASE_SCHEMA:public}
  liquibase:
    change-log: classpath:/db/master.xml
    enabled: ${LIQUIBASE_ENABLED:false}
    drop-first: ${LIQUIBASE_DROP_FIRST:false}
    contexts: ${LIQUIBASE_CONTEXT:local}
  cache:
    type: SIMPLE
  jpa:
    properties:
      hibernate:
        synonyms: true
        default_batch_fetch_size: 100
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        batch_fetch_style: DYNAMIC
        criteria:
          literal_handling_mode: BIND
        connection:
          includeSynonyms: true
          charSet: UTF-8
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}


camunda:
  bpm:
    generic-properties:
      properties:
        historyTimeToLive: P1D
    job-execution:
      core-pool-size: ${CAMUNDA_JOB_EXECUTION_CORE_POOL_SIZE:10}
      max-pool-size: ${CAMUNDA_JOB_EXECUTION_MAX_POOL_SIZE:20}
      queue-capacity: ${CAMUNDA_JOB_EXECUTION_QUEUE_CAPACITY:10}
      max-jobs-per-acquisition: ${CAMUNDA_JOB_EXECUTION_MAX_JOBS_PER_ACQUISITION:10}
      lock-time-in-millis: ${CAMUNDA_JOB_EXECUTION_LOCK_TIME_IN_MILLIS:300000}
      wait-time-in-millis: ${CAMUNDA_JOB_EXECUTION_WAIT_TIME_IN_MILLIS:5000}
      max-wait: ${CAMUNDA_JOB_EXECUTION_MAX_WAIT:30000}
      backoff-time-in-millis: ${CAMUNDA_JOB_EXECUTION_BACKOFF_TIME_IN_MILLIS:0}
      max-backoff: ${CAMUNDA_JOB_EXECUTION_MAX_BACKOFF:0}
      wait-increase-factor: ${CAMUNDA_JOB_EXECUTION_WAIT_INCREASE_FACTOR:1.5}